type = "card"
title = "Friends"

[[items]]
title = "Tiankai Hang"
subtitle = ""
date = ""
content = "ðŸ”— [https://tiankaihang.github.io/](https://tiankaihang.github.io/)"

[[items]]
title = "Jinming Liu"
subtitle = ""
date = ""
content = "ðŸ”— [https://jmliu206.github.io/jmliu.github.io/](https://jmliu206.github.io/jmliu.github.io/)"

[[items]]
title = "Zongyu Guo"
subtitle = ""
date = ""
content = "ðŸ”— [https://zongyuguo.github.io/](https://zongyuguo.github.io/)"
