[[news]]
date = "2024-02"
content = "[CCEdit](https://ruoyufeng.github.io/CCEdit.github.io/) accepted by CVPR 2024"

[[news]]
date = "2024-02"
content = "[MicroCinema](https://wangyanhui666.github.io/MicroCinema.github.io/) accepted by CVPR 2024 as Highlight"

[[news]]
date = "2023-07"
content = "Semantically Structured Image Compression accepted by ICCV 2023"

[[news]]
date = "2023-03"
content = "Started research internship at Microsoft Research Asia"

[[news]]
date = "2022-07"
content = "Image coding for machines with omnipotent feature learning accepted by ECCV 2022"
